# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
---
inherit_from: .rubocop_todo.yml

require:
- rubocop-performance
- rubocop-rake
- rubocop-rspec

AllCops:
  NewCops: enable
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  TargetRubyVersion: '2.7'
  Exclude:
  - vendor/**/*

Gemspec/RequireMFA:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: True
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  Enabled: True
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  Enabled: True
  EnforcedStyleForMultiline: comma
Metrics:
  Description: Metrics cops are rarely useful
  Enabled: false

Style/HashSyntax:
  Description: Disable temporarily (FIXME)
  EnforcedStyle: ruby19
  Enabled: false

Naming/FileName:
  Description: Some files violates the snake_case convention
  Exclude:
    - 'lib/beaker-docker.rb'

Style/IfUnlessModifier:
  Enabled: false
Style/StringLiterals:
  Enabled: false
